server:
  port: 8081 # 服务启动端口

# 数据库链接信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qmock
    username: mrzcode
    password: mrzcode
    driver-class-name: com.mysql.jdbc.Driver

# Mybatis基本配置
mybatis:
  type-aliases-package: cn.daqi.mock.api.entity # 指定实体类所在包
  mapper-locations: classpath:mapper/*.xml # 指定mapper xml 所在位置
  configuration:
    map-underscore-to-camel-case: true  # 数据库表字段自动转驼峰命名 如：user_name -> userName

